# Generated by Django 4.1.4 on 2022-12-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=255)),
                ('airline_name', models.CharField(max_length=255)),
                ('airline_code', models.CharField(max_length=255)),
                ('origin_airport_name', models.CharField(max_length=255)),
                ('origin_airport_code', models.CharField(max_length=255)),
                ('origin_airport_time', models.DateTimeField(blank=True, null=True)),
                ('origin_airport_est_time', models.DateTimeField(blank=True, null=True)),
                ('destination_airport_name', models.CharField(max_length=255)),
                ('destination_airport_code', models.CharField(max_length=255)),
                ('destination_airport_time', models.DateTimeField(blank=True, null=True)),
                ('destination_airport_est_time', models.DateTimeField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, default=0, null=True)),
                ('fare', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('seats', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['created_at'],
            },
        ),
    ]
