# Generated by Django 4.1.4 on 2022-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='weekday',
        ),
        migrations.AddField(
            model_name='flight',
            name='weekdays',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
