# Generated by Django 4.1.4 on 2022-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_weekday_flight_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_airport_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_airport_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_airport_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
